# font=Codelia:size=11.5
# font=Inconsolata Nerd Font:size=14
font=Berkeley Mono SemiLight:size=13
# font=Iosevka Extended:size=13
initial-window-size-chars=304x96

[colors-dark]
alpha=0.98
background=181818

[scrollback]
lines = 9999

[key-bindings]
color-theme-toggle=Control+Shift+l

[main]
include=/usr/share/foot/themes/tempus-dawn
initial-color-theme=dark
