unsetopt beep
bindkey -e
bindkey -v

# Load my functions
if [[ -f $XDG_CONFIG_HOME/zsh/functions.zsh ]]; then
	source $XDG_CONFIG_HOME/zsh/functions.zsh
else
	echo "Function file is missing. Did you stow you zsh config from dotfiles?"
	return 1
fi

if [[ -f $XDG_DATA_HOME/.env ]]; then
    source $XDG_DATA_HOME/.env
else
    echo "Missing ENV file. Make sure this is intentional"
fi

# load_file "prompt.zsh"

load_plugin "zsh-users" "zsh-syntax-highlighting"
load_plugin "zsh-users" "zsh-autosuggestions"

autoload -Uz compinit
compinit

# Path
#
export PATH=~/jai/bin/:~/.local/bin:~/.cargo/bin:$PATH

export LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/lib:~/.local/lib:$LD_LIBRARY_PATH

# Aliases and env
#
alias vim="nvim"
export EDITOR=nvim
export CMAKE_GENERATOR="Ninja"
export ANDROID_HOME=$HOME/Android/Sdk
export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/29.0.13846066

alias wrenderdoc="WAYLAND_DISPLAY= QT_QA_PLATFORM=xcb qrenderdoc"

# Make sure we compile in parallel using make
export MAKEFLAGS=-j$(($(grep -c "^processor" /proc/cpuinfo) - 1))

## ZVM stuff
if [[ -d "$HOME/.zvm" ]]; then
	export ZVM_INSTALL="$HOME/.zvm/self"
	export PATH="$PATH:$HOME/.zvm/bin"
	export PATH="$PATH:$ZVM_INSTALL/"
fi

# Hook callback when keybind is changed
#

function fix_cursor_shape() {
    if [[ $KEYMAP == "vicmd" ]]; then
        echo -ne "\e[2 q"
    else
        echo -ne "\e[3 q"
    fi
}

precmd_function+=(fix_cursor_shape)
zle -N zle-keymap-select fix_cursor_shape
eval $(ssh-agent) >/dev/null
eval "$(starship init zsh)"
